// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5YNt1qsWOBi8v7Au3ub4ith_cqnnvG8c',
    appId: '1:863881504041:web:72d8956b62a76ba3918338',
    messagingSenderId: '863881504041',
    projectId: 'cinepebble-social',
    authDomain: 'cinepebble-social.firebaseapp.com',
    storageBucket: 'cinepebble-social.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-rFFyKd9TV_z_IElvCPGc8hdwYJKqz4A',
    appId: '1:863881504041:android:a1d30130c79d33bd918338',
    messagingSenderId: '863881504041',
    projectId: 'cinepebble-social',
    storageBucket: 'cinepebble-social.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5QCwVAB7ZpFMeU2Q7-R_odvvEPKukFfQ',
    appId: '1:863881504041:ios:07db6ecca7ecb0fa918338',
    messagingSenderId: '863881504041',
    projectId: 'cinepebble-social',
    storageBucket: 'cinepebble-social.appspot.com',
    iosClientId: '863881504041-679e4kj0m7ahhf3ni6o67q0eabrd96dq.apps.googleusercontent.com',
    iosBundleId: 'com.naveenchand.cinepebbleSocial',
  );
}
